################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../AC3AudioFileServerMediaSubsession.o \
../AC3AudioRTPSink.o \
../AC3AudioRTPSource.o \
../AC3AudioStreamFramer.o \
../ADTSAudioFileServerMediaSubsession.o \
../ADTSAudioFileSource.o \
../AMRAudioFileServerMediaSubsession.o \
../AMRAudioFileSink.o \
../AMRAudioFileSource.o \
../AMRAudioRTPSink.o \
../AMRAudioRTPSource.o \
../AMRAudioSource.o \
../AVIFileSink.o \
../AudioInputDevice.o \
../AudioRTPSink.o \
../Base64.o \
../BasicUDPSink.o \
../BasicUDPSource.o \
../BitVector.o \
../ByteStreamFileSource.o \
../ByteStreamMemoryBufferSource.o \
../ByteStreamMultiFileSource.o \
../DVVideoFileServerMediaSubsession.o \
../DVVideoRTPSink.o \
../DVVideoRTPSource.o \
../DVVideoStreamFramer.o \
../DarwinInjector.o \
../DeviceSource.o \
../DigestAuthentication.o \
../EBMLNumber.o \
../FileServerMediaSubsession.o \
../FileSink.o \
../FramedFileSource.o \
../FramedFilter.o \
../FramedSource.o \
../GSMAudioRTPSink.o \
../H261VideoRTPSource.o \
../H263plusVideoFileServerMediaSubsession.o \
../H263plusVideoRTPSink.o \
../H263plusVideoRTPSource.o \
../H263plusVideoStreamFramer.o \
../H263plusVideoStreamParser.o \
../H264VideoFileServerMediaSubsession.o \
../H264VideoFileSink.o \
../H264VideoRTPSink.o \
../H264VideoRTPSource.o \
../H264VideoStreamDiscreteFramer.o \
../H264VideoStreamFramer.o \
../H264or5VideoFileSink.o \
../H264or5VideoRTPSink.o \
../H264or5VideoStreamDiscreteFramer.o \
../H264or5VideoStreamFramer.o \
../H265VideoFileServerMediaSubsession.o \
../H265VideoFileSink.o \
../H265VideoRTPSink.o \
../H265VideoRTPSource.o \
../H265VideoStreamDiscreteFramer.o \
../H265VideoStreamFramer.o \
../InputFile.o \
../JPEGVideoRTPSink.o \
../JPEGVideoRTPSource.o \
../JPEGVideoSource.o \
../Locale.o \
../MP3ADU.o \
../MP3ADURTPSink.o \
../MP3ADURTPSource.o \
../MP3ADUTranscoder.o \
../MP3ADUdescriptor.o \
../MP3ADUinterleaving.o \
../MP3AudioFileServerMediaSubsession.o \
../MP3AudioMatroskaFileServerMediaSubsession.o \
../MP3FileSource.o \
../MP3Internals.o \
../MP3InternalsHuffman.o \
../MP3InternalsHuffmanTable.o \
../MP3StreamState.o \
../MP3Transcoder.o \
../MPEG1or2AudioRTPSink.o \
../MPEG1or2AudioRTPSource.o \
../MPEG1or2AudioStreamFramer.o \
../MPEG1or2Demux.o \
../MPEG1or2DemuxedElementaryStream.o \
../MPEG1or2DemuxedServerMediaSubsession.o \
../MPEG1or2FileServerDemux.o \
../MPEG1or2VideoFileServerMediaSubsession.o \
../MPEG1or2VideoRTPSink.o \
../MPEG1or2VideoRTPSource.o \
../MPEG1or2VideoStreamDiscreteFramer.o \
../MPEG1or2VideoStreamFramer.o \
../MPEG2IndexFromTransportStream.o \
../MPEG2TransportFileServerMediaSubsession.o \
../MPEG2TransportStreamFramer.o \
../MPEG2TransportStreamFromESSource.o \
../MPEG2TransportStreamFromPESSource.o \
../MPEG2TransportStreamIndexFile.o \
../MPEG2TransportStreamMultiplexor.o \
../MPEG2TransportStreamTrickModeFilter.o \
../MPEG2TransportUDPServerMediaSubsession.o \
../MPEG4ESVideoRTPSink.o \
../MPEG4ESVideoRTPSource.o \
../MPEG4GenericRTPSink.o \
../MPEG4GenericRTPSource.o \
../MPEG4LATMAudioRTPSink.o \
../MPEG4LATMAudioRTPSource.o \
../MPEG4VideoFileServerMediaSubsession.o \
../MPEG4VideoStreamDiscreteFramer.o \
../MPEG4VideoStreamFramer.o \
../MPEGVideoStreamFramer.o \
../MPEGVideoStreamParser.o \
../MatroskaDemuxedTrack.o \
../MatroskaFile.o \
../MatroskaFileParser.o \
../MatroskaFileServerDemux.o \
../MatroskaFileServerMediaSubsession.o \
../Media.o \
../MediaSession.o \
../MediaSink.o \
../MediaSource.o \
../MultiFramedRTPSink.o \
../MultiFramedRTPSource.o \
../OggDemuxedTrack.o \
../OggFile.o \
../OggFileParser.o \
../OggFileServerDemux.o \
../OggFileServerMediaSubsession.o \
../OggFileSink.o \
../OnDemandServerMediaSubsession.o \
../OutputFile.o \
../PassiveServerMediaSubsession.o \
../ProxyServerMediaSession.o \
../QCELPAudioRTPSource.o \
../QuickTimeFileSink.o \
../QuickTimeGenericRTPSource.o \
../RTCP.o \
../RTPInterface.o \
../RTPSink.o \
../RTPSource.o \
../RTSPClient.o \
../RTSPCommon.o \
../RTSPRegisterSender.o \
../RTSPServer.o \
../RTSPServerSupportingHTTPStreaming.o \
../SIPClient.o \
../ServerMediaSession.o \
../SimpleRTPSink.o \
../SimpleRTPSource.o \
../StreamParser.o \
../StreamReplicator.o \
../T140TextRTPSink.o \
../TCPStreamSink.o \
../TextRTPSink.o \
../TheoraVideoRTPSink.o \
../TheoraVideoRTPSource.o \
../VP8VideoRTPSink.o \
../VP8VideoRTPSource.o \
../VP9VideoRTPSink.o \
../VP9VideoRTPSource.o \
../VideoRTPSink.o \
../VorbisAudioRTPSink.o \
../VorbisAudioRTPSource.o \
../WAVAudioFileServerMediaSubsession.o \
../WAVAudioFileSource.o \
../ourMD5.o \
../rtcp_from_spec.o \
../uLawAudioFilter.o 

CPP_SRCS += \
../AC3AudioFileServerMediaSubsession.cpp \
../AC3AudioRTPSink.cpp \
../AC3AudioRTPSource.cpp \
../AC3AudioStreamFramer.cpp \
../ADTSAudioFileServerMediaSubsession.cpp \
../ADTSAudioFileSource.cpp \
../AMRAudioFileServerMediaSubsession.cpp \
../AMRAudioFileSink.cpp \
../AMRAudioFileSource.cpp \
../AMRAudioRTPSink.cpp \
../AMRAudioRTPSource.cpp \
../AMRAudioSource.cpp \
../AVIFileSink.cpp \
../AudioInputDevice.cpp \
../AudioRTPSink.cpp \
../Base64.cpp \
../BasicUDPSink.cpp \
../BasicUDPSource.cpp \
../BitVector.cpp \
../ByteStreamFileSource.cpp \
../ByteStreamMemoryBufferSource.cpp \
../ByteStreamMultiFileSource.cpp \
../DVVideoFileServerMediaSubsession.cpp \
../DVVideoRTPSink.cpp \
../DVVideoRTPSource.cpp \
../DVVideoStreamFramer.cpp \
../DarwinInjector.cpp \
../DeviceSource.cpp \
../DigestAuthentication.cpp \
../EBMLNumber.cpp \
../FileServerMediaSubsession.cpp \
../FileSink.cpp \
../FramedFileSource.cpp \
../FramedFilter.cpp \
../FramedSource.cpp \
../GSMAudioRTPSink.cpp \
../H261VideoRTPSource.cpp \
../H263plusVideoFileServerMediaSubsession.cpp \
../H263plusVideoRTPSink.cpp \
../H263plusVideoRTPSource.cpp \
../H263plusVideoStreamFramer.cpp \
../H263plusVideoStreamParser.cpp \
../H264VideoFileServerMediaSubsession.cpp \
../H264VideoFileSink.cpp \
../H264VideoRTPSink.cpp \
../H264VideoRTPSource.cpp \
../H264VideoStreamDiscreteFramer.cpp \
../H264VideoStreamFramer.cpp \
../H264or5VideoFileSink.cpp \
../H264or5VideoRTPSink.cpp \
../H264or5VideoStreamDiscreteFramer.cpp \
../H264or5VideoStreamFramer.cpp \
../H265VideoFileServerMediaSubsession.cpp \
../H265VideoFileSink.cpp \
../H265VideoRTPSink.cpp \
../H265VideoRTPSource.cpp \
../H265VideoStreamDiscreteFramer.cpp \
../H265VideoStreamFramer.cpp \
../InputFile.cpp \
../JPEGVideoRTPSink.cpp \
../JPEGVideoRTPSource.cpp \
../JPEGVideoSource.cpp \
../Locale.cpp \
../MP3ADU.cpp \
../MP3ADURTPSink.cpp \
../MP3ADURTPSource.cpp \
../MP3ADUTranscoder.cpp \
../MP3ADUdescriptor.cpp \
../MP3ADUinterleaving.cpp \
../MP3AudioFileServerMediaSubsession.cpp \
../MP3AudioMatroskaFileServerMediaSubsession.cpp \
../MP3FileSource.cpp \
../MP3Internals.cpp \
../MP3InternalsHuffman.cpp \
../MP3InternalsHuffmanTable.cpp \
../MP3StreamState.cpp \
../MP3Transcoder.cpp \
../MPEG1or2AudioRTPSink.cpp \
../MPEG1or2AudioRTPSource.cpp \
../MPEG1or2AudioStreamFramer.cpp \
../MPEG1or2Demux.cpp \
../MPEG1or2DemuxedElementaryStream.cpp \
../MPEG1or2DemuxedServerMediaSubsession.cpp \
../MPEG1or2FileServerDemux.cpp \
../MPEG1or2VideoFileServerMediaSubsession.cpp \
../MPEG1or2VideoRTPSink.cpp \
../MPEG1or2VideoRTPSource.cpp \
../MPEG1or2VideoStreamDiscreteFramer.cpp \
../MPEG1or2VideoStreamFramer.cpp \
../MPEG2IndexFromTransportStream.cpp \
../MPEG2TransportFileServerMediaSubsession.cpp \
../MPEG2TransportStreamFramer.cpp \
../MPEG2TransportStreamFromESSource.cpp \
../MPEG2TransportStreamFromPESSource.cpp \
../MPEG2TransportStreamIndexFile.cpp \
../MPEG2TransportStreamMultiplexor.cpp \
../MPEG2TransportStreamTrickModeFilter.cpp \
../MPEG2TransportUDPServerMediaSubsession.cpp \
../MPEG4ESVideoRTPSink.cpp \
../MPEG4ESVideoRTPSource.cpp \
../MPEG4GenericRTPSink.cpp \
../MPEG4GenericRTPSource.cpp \
../MPEG4LATMAudioRTPSink.cpp \
../MPEG4LATMAudioRTPSource.cpp \
../MPEG4VideoFileServerMediaSubsession.cpp \
../MPEG4VideoStreamDiscreteFramer.cpp \
../MPEG4VideoStreamFramer.cpp \
../MPEGVideoStreamFramer.cpp \
../MPEGVideoStreamParser.cpp \
../MatroskaDemuxedTrack.cpp \
../MatroskaFile.cpp \
../MatroskaFileParser.cpp \
../MatroskaFileServerDemux.cpp \
../MatroskaFileServerMediaSubsession.cpp \
../Media.cpp \
../MediaSession.cpp \
../MediaSink.cpp \
../MediaSource.cpp \
../MultiFramedRTPSink.cpp \
../MultiFramedRTPSource.cpp \
../OggDemuxedTrack.cpp \
../OggFile.cpp \
../OggFileParser.cpp \
../OggFileServerDemux.cpp \
../OggFileServerMediaSubsession.cpp \
../OggFileSink.cpp \
../OnDemandServerMediaSubsession.cpp \
../OutputFile.cpp \
../PassiveServerMediaSubsession.cpp \
../ProxyServerMediaSession.cpp \
../QCELPAudioRTPSource.cpp \
../QuickTimeFileSink.cpp \
../QuickTimeGenericRTPSource.cpp \
../RTCP.cpp \
../RTPInterface.cpp \
../RTPSink.cpp \
../RTPSource.cpp \
../RTSPClient.cpp \
../RTSPCommon.cpp \
../RTSPRegisterSender.cpp \
../RTSPServer.cpp \
../RTSPServerSupportingHTTPStreaming.cpp \
../SIPClient.cpp \
../ServerMediaSession.cpp \
../SimpleRTPSink.cpp \
../SimpleRTPSource.cpp \
../StreamParser.cpp \
../StreamReplicator.cpp \
../T140TextRTPSink.cpp \
../TCPStreamSink.cpp \
../TextRTPSink.cpp \
../TheoraVideoRTPSink.cpp \
../TheoraVideoRTPSource.cpp \
../VP8VideoRTPSink.cpp \
../VP8VideoRTPSource.cpp \
../VP9VideoRTPSink.cpp \
../VP9VideoRTPSource.cpp \
../VideoRTPSink.cpp \
../VorbisAudioRTPSink.cpp \
../VorbisAudioRTPSource.cpp \
../WAVAudioFileServerMediaSubsession.cpp \
../WAVAudioFileSource.cpp \
../ourMD5.cpp \
../uLawAudioFilter.cpp 

C_SRCS += \
../main.c \
../rtcp_from_spec.c 

OBJS += \
./AC3AudioFileServerMediaSubsession.o \
./AC3AudioRTPSink.o \
./AC3AudioRTPSource.o \
./AC3AudioStreamFramer.o \
./ADTSAudioFileServerMediaSubsession.o \
./ADTSAudioFileSource.o \
./AMRAudioFileServerMediaSubsession.o \
./AMRAudioFileSink.o \
./AMRAudioFileSource.o \
./AMRAudioRTPSink.o \
./AMRAudioRTPSource.o \
./AMRAudioSource.o \
./AVIFileSink.o \
./AudioInputDevice.o \
./AudioRTPSink.o \
./Base64.o \
./BasicUDPSink.o \
./BasicUDPSource.o \
./BitVector.o \
./ByteStreamFileSource.o \
./ByteStreamMemoryBufferSource.o \
./ByteStreamMultiFileSource.o \
./DVVideoFileServerMediaSubsession.o \
./DVVideoRTPSink.o \
./DVVideoRTPSource.o \
./DVVideoStreamFramer.o \
./DarwinInjector.o \
./DeviceSource.o \
./DigestAuthentication.o \
./EBMLNumber.o \
./FileServerMediaSubsession.o \
./FileSink.o \
./FramedFileSource.o \
./FramedFilter.o \
./FramedSource.o \
./GSMAudioRTPSink.o \
./H261VideoRTPSource.o \
./H263plusVideoFileServerMediaSubsession.o \
./H263plusVideoRTPSink.o \
./H263plusVideoRTPSource.o \
./H263plusVideoStreamFramer.o \
./H263plusVideoStreamParser.o \
./H264VideoFileServerMediaSubsession.o \
./H264VideoFileSink.o \
./H264VideoRTPSink.o \
./H264VideoRTPSource.o \
./H264VideoStreamDiscreteFramer.o \
./H264VideoStreamFramer.o \
./H264or5VideoFileSink.o \
./H264or5VideoRTPSink.o \
./H264or5VideoStreamDiscreteFramer.o \
./H264or5VideoStreamFramer.o \
./H265VideoFileServerMediaSubsession.o \
./H265VideoFileSink.o \
./H265VideoRTPSink.o \
./H265VideoRTPSource.o \
./H265VideoStreamDiscreteFramer.o \
./H265VideoStreamFramer.o \
./InputFile.o \
./JPEGVideoRTPSink.o \
./JPEGVideoRTPSource.o \
./JPEGVideoSource.o \
./Locale.o \
./MP3ADU.o \
./MP3ADURTPSink.o \
./MP3ADURTPSource.o \
./MP3ADUTranscoder.o \
./MP3ADUdescriptor.o \
./MP3ADUinterleaving.o \
./MP3AudioFileServerMediaSubsession.o \
./MP3AudioMatroskaFileServerMediaSubsession.o \
./MP3FileSource.o \
./MP3Internals.o \
./MP3InternalsHuffman.o \
./MP3InternalsHuffmanTable.o \
./MP3StreamState.o \
./MP3Transcoder.o \
./MPEG1or2AudioRTPSink.o \
./MPEG1or2AudioRTPSource.o \
./MPEG1or2AudioStreamFramer.o \
./MPEG1or2Demux.o \
./MPEG1or2DemuxedElementaryStream.o \
./MPEG1or2DemuxedServerMediaSubsession.o \
./MPEG1or2FileServerDemux.o \
./MPEG1or2VideoFileServerMediaSubsession.o \
./MPEG1or2VideoRTPSink.o \
./MPEG1or2VideoRTPSource.o \
./MPEG1or2VideoStreamDiscreteFramer.o \
./MPEG1or2VideoStreamFramer.o \
./MPEG2IndexFromTransportStream.o \
./MPEG2TransportFileServerMediaSubsession.o \
./MPEG2TransportStreamFramer.o \
./MPEG2TransportStreamFromESSource.o \
./MPEG2TransportStreamFromPESSource.o \
./MPEG2TransportStreamIndexFile.o \
./MPEG2TransportStreamMultiplexor.o \
./MPEG2TransportStreamTrickModeFilter.o \
./MPEG2TransportUDPServerMediaSubsession.o \
./MPEG4ESVideoRTPSink.o \
./MPEG4ESVideoRTPSource.o \
./MPEG4GenericRTPSink.o \
./MPEG4GenericRTPSource.o \
./MPEG4LATMAudioRTPSink.o \
./MPEG4LATMAudioRTPSource.o \
./MPEG4VideoFileServerMediaSubsession.o \
./MPEG4VideoStreamDiscreteFramer.o \
./MPEG4VideoStreamFramer.o \
./MPEGVideoStreamFramer.o \
./MPEGVideoStreamParser.o \
./MatroskaDemuxedTrack.o \
./MatroskaFile.o \
./MatroskaFileParser.o \
./MatroskaFileServerDemux.o \
./MatroskaFileServerMediaSubsession.o \
./Media.o \
./MediaSession.o \
./MediaSink.o \
./MediaSource.o \
./MultiFramedRTPSink.o \
./MultiFramedRTPSource.o \
./OggDemuxedTrack.o \
./OggFile.o \
./OggFileParser.o \
./OggFileServerDemux.o \
./OggFileServerMediaSubsession.o \
./OggFileSink.o \
./OnDemandServerMediaSubsession.o \
./OutputFile.o \
./PassiveServerMediaSubsession.o \
./ProxyServerMediaSession.o \
./QCELPAudioRTPSource.o \
./QuickTimeFileSink.o \
./QuickTimeGenericRTPSource.o \
./RTCP.o \
./RTPInterface.o \
./RTPSink.o \
./RTPSource.o \
./RTSPClient.o \
./RTSPCommon.o \
./RTSPRegisterSender.o \
./RTSPServer.o \
./RTSPServerSupportingHTTPStreaming.o \
./SIPClient.o \
./ServerMediaSession.o \
./SimpleRTPSink.o \
./SimpleRTPSource.o \
./StreamParser.o \
./StreamReplicator.o \
./T140TextRTPSink.o \
./TCPStreamSink.o \
./TextRTPSink.o \
./TheoraVideoRTPSink.o \
./TheoraVideoRTPSource.o \
./VP8VideoRTPSink.o \
./VP8VideoRTPSource.o \
./VP9VideoRTPSink.o \
./VP9VideoRTPSource.o \
./VideoRTPSink.o \
./VorbisAudioRTPSink.o \
./VorbisAudioRTPSource.o \
./WAVAudioFileServerMediaSubsession.o \
./WAVAudioFileSource.o \
./main.o \
./ourMD5.o \
./rtcp_from_spec.o \
./uLawAudioFilter.o 

C_DEPS += \
./main.d \
./rtcp_from_spec.d 

CPP_DEPS += \
./AC3AudioFileServerMediaSubsession.d \
./AC3AudioRTPSink.d \
./AC3AudioRTPSource.d \
./AC3AudioStreamFramer.d \
./ADTSAudioFileServerMediaSubsession.d \
./ADTSAudioFileSource.d \
./AMRAudioFileServerMediaSubsession.d \
./AMRAudioFileSink.d \
./AMRAudioFileSource.d \
./AMRAudioRTPSink.d \
./AMRAudioRTPSource.d \
./AMRAudioSource.d \
./AVIFileSink.d \
./AudioInputDevice.d \
./AudioRTPSink.d \
./Base64.d \
./BasicUDPSink.d \
./BasicUDPSource.d \
./BitVector.d \
./ByteStreamFileSource.d \
./ByteStreamMemoryBufferSource.d \
./ByteStreamMultiFileSource.d \
./DVVideoFileServerMediaSubsession.d \
./DVVideoRTPSink.d \
./DVVideoRTPSource.d \
./DVVideoStreamFramer.d \
./DarwinInjector.d \
./DeviceSource.d \
./DigestAuthentication.d \
./EBMLNumber.d \
./FileServerMediaSubsession.d \
./FileSink.d \
./FramedFileSource.d \
./FramedFilter.d \
./FramedSource.d \
./GSMAudioRTPSink.d \
./H261VideoRTPSource.d \
./H263plusVideoFileServerMediaSubsession.d \
./H263plusVideoRTPSink.d \
./H263plusVideoRTPSource.d \
./H263plusVideoStreamFramer.d \
./H263plusVideoStreamParser.d \
./H264VideoFileServerMediaSubsession.d \
./H264VideoFileSink.d \
./H264VideoRTPSink.d \
./H264VideoRTPSource.d \
./H264VideoStreamDiscreteFramer.d \
./H264VideoStreamFramer.d \
./H264or5VideoFileSink.d \
./H264or5VideoRTPSink.d \
./H264or5VideoStreamDiscreteFramer.d \
./H264or5VideoStreamFramer.d \
./H265VideoFileServerMediaSubsession.d \
./H265VideoFileSink.d \
./H265VideoRTPSink.d \
./H265VideoRTPSource.d \
./H265VideoStreamDiscreteFramer.d \
./H265VideoStreamFramer.d \
./InputFile.d \
./JPEGVideoRTPSink.d \
./JPEGVideoRTPSource.d \
./JPEGVideoSource.d \
./Locale.d \
./MP3ADU.d \
./MP3ADURTPSink.d \
./MP3ADURTPSource.d \
./MP3ADUTranscoder.d \
./MP3ADUdescriptor.d \
./MP3ADUinterleaving.d \
./MP3AudioFileServerMediaSubsession.d \
./MP3AudioMatroskaFileServerMediaSubsession.d \
./MP3FileSource.d \
./MP3Internals.d \
./MP3InternalsHuffman.d \
./MP3InternalsHuffmanTable.d \
./MP3StreamState.d \
./MP3Transcoder.d \
./MPEG1or2AudioRTPSink.d \
./MPEG1or2AudioRTPSource.d \
./MPEG1or2AudioStreamFramer.d \
./MPEG1or2Demux.d \
./MPEG1or2DemuxedElementaryStream.d \
./MPEG1or2DemuxedServerMediaSubsession.d \
./MPEG1or2FileServerDemux.d \
./MPEG1or2VideoFileServerMediaSubsession.d \
./MPEG1or2VideoRTPSink.d \
./MPEG1or2VideoRTPSource.d \
./MPEG1or2VideoStreamDiscreteFramer.d \
./MPEG1or2VideoStreamFramer.d \
./MPEG2IndexFromTransportStream.d \
./MPEG2TransportFileServerMediaSubsession.d \
./MPEG2TransportStreamFramer.d \
./MPEG2TransportStreamFromESSource.d \
./MPEG2TransportStreamFromPESSource.d \
./MPEG2TransportStreamIndexFile.d \
./MPEG2TransportStreamMultiplexor.d \
./MPEG2TransportStreamTrickModeFilter.d \
./MPEG2TransportUDPServerMediaSubsession.d \
./MPEG4ESVideoRTPSink.d \
./MPEG4ESVideoRTPSource.d \
./MPEG4GenericRTPSink.d \
./MPEG4GenericRTPSource.d \
./MPEG4LATMAudioRTPSink.d \
./MPEG4LATMAudioRTPSource.d \
./MPEG4VideoFileServerMediaSubsession.d \
./MPEG4VideoStreamDiscreteFramer.d \
./MPEG4VideoStreamFramer.d \
./MPEGVideoStreamFramer.d \
./MPEGVideoStreamParser.d \
./MatroskaDemuxedTrack.d \
./MatroskaFile.d \
./MatroskaFileParser.d \
./MatroskaFileServerDemux.d \
./MatroskaFileServerMediaSubsession.d \
./Media.d \
./MediaSession.d \
./MediaSink.d \
./MediaSource.d \
./MultiFramedRTPSink.d \
./MultiFramedRTPSource.d \
./OggDemuxedTrack.d \
./OggFile.d \
./OggFileParser.d \
./OggFileServerDemux.d \
./OggFileServerMediaSubsession.d \
./OggFileSink.d \
./OnDemandServerMediaSubsession.d \
./OutputFile.d \
./PassiveServerMediaSubsession.d \
./ProxyServerMediaSession.d \
./QCELPAudioRTPSource.d \
./QuickTimeFileSink.d \
./QuickTimeGenericRTPSource.d \
./RTCP.d \
./RTPInterface.d \
./RTPSink.d \
./RTPSource.d \
./RTSPClient.d \
./RTSPCommon.d \
./RTSPRegisterSender.d \
./RTSPServer.d \
./RTSPServerSupportingHTTPStreaming.d \
./SIPClient.d \
./ServerMediaSession.d \
./SimpleRTPSink.d \
./SimpleRTPSource.d \
./StreamParser.d \
./StreamReplicator.d \
./T140TextRTPSink.d \
./TCPStreamSink.d \
./TextRTPSink.d \
./TheoraVideoRTPSink.d \
./TheoraVideoRTPSource.d \
./VP8VideoRTPSink.d \
./VP8VideoRTPSource.d \
./VP9VideoRTPSink.d \
./VP9VideoRTPSource.d \
./VideoRTPSink.d \
./VorbisAudioRTPSink.d \
./VorbisAudioRTPSource.d \
./WAVAudioFileServerMediaSubsession.d \
./WAVAudioFileSource.d \
./ourMD5.d \
./uLawAudioFilter.d 


# Each subdirectory must supply rules for building sources it contributes
%.o: ../%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -I"/mnt/data/steven/workspace/2 MGV/live/liveMedia/include" -I"/mnt/data/steven/workspace/2 MGV/live/groupsock/include" -I"/mnt/data/steven/workspace/2 MGV/live/UsageEnvironment/include" -I"/mnt/data/steven/workspace/2 MGV/live/BasicUsageEnvironment/include" -O3 -Wall -c -fmessage-length=0 -fpermissive -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

%.o: ../%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C Compiler'
	gcc -I"/mnt/data/steven/workspace/2 MGV/live/groupsock" -I"/mnt/data/steven/workspace/2 MGV/live/UsageEnvironment" -I"/mnt/data/steven/workspace/2 MGV/live/BasicUsageEnvironment" -I"/mnt/data/steven/workspace/2 MGV/live/liveMedia/include" -I"/mnt/data/steven/workspace/2 MGV/live/groupsock/include" -I"/mnt/data/steven/workspace/2 MGV/live/UsageEnvironment/include" -I"/mnt/data/steven/workspace/2 MGV/live/BasicUsageEnvironment/include" -O3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


